- hosts: "{{ h }}"

  pre_tasks:
  - name: Install pycurl
    apt: pkg=python-pycurl update_cache=yes cache_valid_time=600

  roles:
  - role: forge_hostname
  - role: angstwad.docker_ubuntu
  - role: dockerdemo
    tags: app
